### ISSUE TITLE
Merge Sort Algorithm

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#13]

**Comment by Harsh-Aakoliya** [comment]
Kindly assign this issue to me.

**Comment by shrinidhihegde3** [comment]
You will be assigned on 1st Oct since event starts from that day

**Comment by shrinidhihegde3** [comment]
create a file inside snippets/Algorithms called mergeSort.tsx and contribute your code use different coding languages as well

**Comment by Harsh-Aakoliya** [comment]
Please review the PR : https://github.com/shrinidhihegde3/Snippify-Hub/pull/32
