### ISSUE TITLE
 Depth-First Search (DFS) Algorithm

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#14]

**Comment by yatinsharmaa12** [comment]
Hey @shrinidhihegde3, I am interested in working on this issue, but I need more clarity. Can I just add logic in C++, Java, and Python?

**Comment by shrinidhihegde3** [comment]
You can add algorithm in multiple languages like c++, java python and all make sure you include all these in one file only do create multiple files for different languages
Create file DepthFirstSearch.tsx inside snippets and add contribute
make sure to add reference link, how to use, use case and all
