### ISSUE TITLE
JavaScript Snippet: OAuth2 Authorization Code Flow

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#15]
Demonstrate how to implement OAuth2 Authorization Code Flow using a JavaScript client.

**Comment by kajal-jotwani** [comment]
can i work on this issue?

**Comment by shrinidhihegde3** [comment]
Use passportjs or any other.. add steps to implement

**Comment by shrinidhihegde3** [comment]
any updates?

**Comment by kajal-jotwani** [comment]
yaa I have a few changes to make and I'll make the pr positively by tomorrow
