### ISSUE TITLE
Bellman-Ford Algorithm

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#18]
Provide a code snippet for the Bellman-Ford algorithm, which computes the shortest paths from a single source vertex to all other vertices in a weighted graph.

**Comment by yatinsharmaa12** [comment]
hey @shrinidhihegde3  i would like to work on this issue. can you assign it to me ?

**Comment by shrinidhihegde3** [comment]
Assigned. Create a file called bellmanFord.tsx inside snippets/algorithms can contribute there also you can use different languages as well

**Comment by yatinsharmaa12** [comment]
I have used C++ for now .

**Comment by shrinidhihegde3** [comment]
ok ...Did you go through bubbleSort.tsx ? how it is made using codeSnippet component and all

**Comment by shrinidhihegde3** [comment]
and attach screenshots in pr

**Comment by yatinsharmaa12** [comment]
yes, I have gone through bubbleSort.tsx . I have added CodeSnippet component and same Ui as BubbleSort.tsx . I havent passsed it app.tsx as UI is not fixed
