### ISSUE TITLE
WebSocket Implementation for Real-Time Communication

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#21]
Provide a WebSocket implementation in JavaScript to enable real-time communication between a server and a client.

**Comment by kajal-jotwani** [comment]
can you please describe the issue a little more? I would like to work on this issue

**Comment by shrinidhihegde3** [comment]
Websockets are a communication protocol that enable bidirectional communication between applications. So your job is to implement websocket code snippet explain how to use, use case, reference and all

**Comment by kajal-jotwani** [comment]
Hey, do I need to add code snippets for both client-side and server-side WebSockets?

**Comment by shrinidhihegde3** [comment]
Yeaa you can do that too
