### ISSUE TITLE
Create one responsive navbar with logo and search bar

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#22]

**Comment by Rajmathur-8** [comment]
I want to work on this issue. Can you please assign me this ?

**Comment by shrinidhihegde3** [comment]
Create a file inside components called navbar.tsx and contribute your code use gif logo in the navbar located in assets folder

**Comment by shrinidhihegde3** [comment]
add issue number in your pr and also attach screenshots

**Comment by Rajmathur-8** [comment]
issue number - #22
![Screenshot 2024-10-01 182626](https://github.com/user-attachments/assets/d1c5dc0f-fd3c-4f92-bf0b-aa7076ded572)
Is it ok ?

**Comment by Rajmathur-8** [comment]
Which type of Search functionality do you want in it? like on which basic as it has only single page..

**Comment by shrinidhihegde3** [comment]
i am trying to implement issue #26. So when searched in search the box should appear

**Comment by Rajmathur-8** [comment]
okk
