### ISSUE TITLE
Caesar Cipher

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#40]
A substitution cipher where each letter in the plaintext is shifted by a fixed number of positions down or up the alphabet.
add input and output field also so that people can experiment.

**Comment by sahuf2003** [comment]
@shrinidhihegde3  I would like to work on this

**Comment by shrinidhihegde3** [comment]
Implement inside snippets/ciphers folder

**Comment by shrinidhihegde3** [comment]
in input field make it both ways encryption and decryption

**Comment by sahuf2003** [comment]
ok i will do it
