### ISSUE TITLE
Vigenère Cipher

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#41]
A polyalphabetic substitution cipher where each letter in the plaintext is shifted according to a key, which repeats cyclically. 
Add input and output field also so that people can experiment

**Comment by Rajmathur-8** [comment]
Hey are you needing something like this ? if yes then can you please assign me this.
![Screenshot 2024-10-03 010337](https://github.com/user-attachments/assets/2b36803f-72c9-401c-960f-6e40a8e10eed)
I can style it accordingly and add it to your website...

**Comment by shrinidhihegde3** [comment]
assigned you can contribute in snippets/ciphers folder

**Comment by shrinidhihegde3** [comment]
Make it in both ways encryption and decryption

**Comment by shrinidhihegde3** [comment]
any updates?

**Comment by Rajmathur-8** [comment]
is it good
![Screenshot 2024-10-20 120829](https://github.com/user-attachments/assets/9e5bfe1e-8ea7-4323-907d-1d2124593f02)
![Screenshot 2024-10-20 120852](https://github.com/user-attachments/assets/b574be86-023a-445b-9061-ab8668b64c25)

**Comment by Rajmathur-8** [comment]
both are there encrypt and decrypt also added its code in cpp,java and python

**Comment by shrinidhihegde3** [comment]
Add detailed explanation where and how it is used, reference use case and all

**Comment by Rajmathur-8** [comment]
will this do?
![Screenshot 2024-10-21 014606](https://github.com/user-attachments/assets/591b7b31-61f8-496c-98c5-8229e16a601a)
![Screenshot 2024-10-21 014619](https://github.com/user-attachments/assets/ca4fbb6b-1325-48aa-8db6-09c712d2310e)
