### ISSUE TITLE
Advanced Encryption Standard (AES)

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#46]
A symmetric encryption algorithm used in modern encryption protocols. It encrypts data in blocks of 128 bits using keys of 128, 192, or 256 bits.
Add input and output field also so that people can experiment

**Comment by Rajmathur-8** [comment]
hey @shrinidhihegde3  can you assign me this.
if this is what u are needing
![Screenshot 2024-10-20 154906](https://github.com/user-attachments/assets/d8d4369f-a80e-4648-a8a4-76194e54a43d)
![Screenshot 2024-10-20 154931](https://github.com/user-attachments/assets/1239d418-aa60-4479-8eac-617c38f39a82)

**Comment by shrinidhihegde3** [comment]
Same goes here add code how this is implemented (no use of builtin function)
Add detailed explanations.

**Comment by Rajmathur-8** [comment]
![Screenshot 2024-10-21 153807](https://github.com/user-attachments/assets/29975099-1905-45e0-a24f-ea56fc8f9ee0)
![Screenshot 2024-10-21 153833](https://github.com/user-attachments/assets/17f0e155-a0ca-49c2-ae03-e4f060512bbc)
![Screenshot 2024-10-21 153856](https://github.com/user-attachments/assets/33faf959-c998-4ac9-bd98-546689591ba4)
will this do?

**Comment by shrinidhihegde3** [comment]
yea this works
