### ISSUE TITLE
Breadth First Search 

### ISSUE THREAD

**Issue by Harsh-Aakoliya** [shrinidhihegde3/Snippify-Hub#52]
Similar to the Depth First Search Algorithm we can add the BFS algorithm.

**Comment by Harsh-Aakoliya** [comment]
If you wish to implement it then kindly assign it to me

**Comment by shrinidhihegde3** [comment]
can you do one more with this?

**Comment by Harsh-Aakoliya** [comment]
yes!

**Comment by shrinidhihegde3** [comment]
which one will you do with current one?
