### ISSUE TITLE
Vernam Cipher (One-Time Pad)

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#61]
A theoretically unbreakable cipher where each character of the plaintext is combined with a random character from a key that is as long as the message.
Add input and output field so that people can experiment

**Comment by Nisha-Rao21** [comment]
Hi @shrinidhihegde3, I would like to work on this. Please assign it to me

**Comment by shrinidhihegde3** [comment]
Assigned
