### ISSUE TITLE
SHA-3 (Secure Hash Algorithm 3)

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#66]
A cryptographic hash function that generates a fixed-size hash from variable input data. It’s part of the SHA family and offers higher security.
Add input and output field so that people can experiment

**Comment by Rajmathur-8** [comment]
will this do...?
![Screenshot 2024-10-20 154040](https://github.com/user-attachments/assets/fa3a4dfa-3862-4529-9ee5-46d5f4a8e32c)

**Comment by Rajmathur-8** [comment]
if this will do please assign me to it and i wll complete it today..

**Comment by shrinidhihegde3** [comment]
Need detailed explanation of this cipher/hash how to implement, where it is used, benefits, how secure it is, any reference..
Also try to add code of keccak function which is used in sha- hash

**Comment by Rajmathur-8** [comment]
![Screenshot 2024-10-21 154101](https://github.com/user-attachments/assets/b378e77a-5785-43f2-a79e-84e418870202)
![Screenshot 2024-10-21 154112](https://github.com/user-attachments/assets/77c4cd92-d26c-41f4-8e93-42415057d9ba)
![Screenshot 2024-10-21 154127](https://github.com/user-attachments/assets/47b3c52f-3c3a-45d9-8a22-fe21c570a539)
![Screenshot 2024-10-21 154647](https://github.com/user-attachments/assets/30815760-6507-4d1a-b68c-ae108c0107be)
will this do ??

**Comment by shrinidhihegde3** [comment]
yea this works
