### ISSUE TITLE
Basic Web Scraper with BeautifulSoup

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#7]
Provide a Python code snippet that shows how to scrape a simple webpage using BeautifulSoup.

**Comment by yashksaini-coder** [comment]
I would like to work on this issue @shrinidhihegde3 I have intermediate knowledge of python, and have done web scraping in the past.

**Comment by shrinidhihegde3** [comment]
assigned
