### ISSUE TITLE
Fix dashboard page for Responsive mode

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#75]
issues are - 
- Text Overflowing
- Last Row display of box is being shorted

**Comment by KAMAL-02** [comment]
Kindly assign it to me

**Comment by shrinidhihegde3** [comment]
assigned

**Comment by KAMAL-02** [comment]
Hey using grid-cols-3 makes the layout feel quite compact on mobile devices. Instead we can display  one or two cards per row to provide more breathing space and improve responsiveness. Furthermore we can truncate long titles to ensure they fit neatly within the cards thus enhancing the overall appearance

![image](https://github.com/user-attachments/assets/c5d354de-028e-46ea-845e-19dcbc7b30a6)
