### ISSUE TITLE
Add a JavaScript Snippet: Fetch API

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#8]
Provide a code snippet that demonstrates how to use the Fetch API to make a GET request and handle responses.

**Comment by ajay0180** [comment]
Kindly ,assign this issue to me.

**Comment by shrinidhihegde3** [comment]
Assigned. Create a file inside snippets/web called fetchAPI.tsx and work with different languages

**Comment by ajay0180** [comment]
I have made a pull request, so,  review it and let me know if any modifications are required. Thanks!

**Comment by ajay0180** [comment]
I am going to make pull request again,I have done all stuffs and changes you tell me. Kindly give me feedback

**Comment by shrinidhihegde3** [comment]
merged
