### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by shrinidhihegde3** [shrinidhihegde3/Snippify-Hub#85]
- Add footer with sliding window where contributors github profile should be displayed dynamically from contributors list
- when clicked on the profile it should redirect to their respective github profile

**Comment by kartik1112** [comment]
hi @shrinidhihegde3 I would like to pick this feature do you have any idea for reference ?

**Comment by shrinidhihegde3** [comment]
https://api.github.com/repos/shrinidhihegde3/snippify-hub/contributors

Run the above link in the browser you will idea...

Use this api for collecting all the information and display in footer.

https://nmithacks.com/
Check this for how slider works 
At the bottom of the page there will be organisers profile just sliding..

**Comment by kartik1112** [comment]
Yes please I'll do it
